[package]
name = "warp-taskbar"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.18.2"
image = "0.25.5"
tray-icon = "0.20.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
home = "0.5"
